Repository SSantosLab/Main-Injector, pull requests merged in 2024-05, with the labels that each got.

#61 60 website add trigger fix
  handlers/gwstreamer.py
  python/OneRing.py
  recycler.py
Labels: bug, High Priority

#65 Add website slackbot message
  handlers/gwstreamer.py
Labels: enhancement, Medium Priority

#66 56 bayestar injection priors
  test_hexes/bayestar_injection.sh
  test_hexes/mock_bayestar_event.py
Labels: bug, Medium Priority
